name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Check
              run: cargo check

            - name: Test
              run: cargo test

            - name: Build
              run: cargo build --release

            - name: Clippy
              run: cargo clippy -- -D warnings

            - name: Format check
              run: cargo fmt -- --check
